# Generated by Django 6.0.3 on 2026-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Health"),
                            ("nutrition", "Nutrition"),
                            ("fitness", "Fitness"),
                            ("mental_health", "Mental Health"),
                            ("heart_health", "Heart Health"),
                            ("diabetes", "Diabetes"),
                            ("hygiene", "Hygiene"),
                            ("sleep", "Sleep"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("icon", models.CharField(blank=True, default="💊", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
